# stock historical data

In [1]:

from credentials import api_key,secret_key
from alpaca.data.historical.stock import StockHistoricalDataClient

# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key)

In [ ]:
from datetime import datetime,timedelta
from zoneinfo import ZoneInfo
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit

symbol = "GOOG"
# get historical bars by symbol
# ref. https://docs.alpaca.markets/reference/stockbars-1
now = datetime.now(ZoneInfo("America/New_York"))
req = StockBarsRequest(
    symbol_or_symbols = symbol,
    timeframe=TimeFrame(amount = 5, unit = TimeFrameUnit.Minute), # specify timeframe
    start = now - timedelta(days = 100),                          # specify start datetime, default=the beginning of the current day.
    # end_date=None,                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)
history_df1=stock_historical_data_client.get_stock_bars(req).df
history_df1

                                     open      high       low     close  \
symbol timestamp
GOOG   2024-09-19 12:30:00+00:00  164.490  164.5760  164.4500  164.5760
       2024-09-19 12:35:00+00:00  164.520  164.6400  164.5000  164.6400
       2024-09-19 12:40:00+00:00  164.670  164.7000  164.5900  164.6500
       2024-09-19 12:45:00+00:00  164.630  164.6500  164.5000  164.5000
       2024-09-19 12:50:00+00:00  164.587  164.5993  164.4630  164.5993
...                                   ...       ...       ...       ...
       2024-12-28 00:25:00+00:00  194.210  194.2100  194.2100  194.2100
       2024-12-28 00:40:00+00:00  194.100  194.1000  194.1000  194.1000
       2024-12-28 00:45:00+00:00  194.030  194.0400  194.0300  194.0400
       2024-12-28 00:50:00+00:00  194.030  194.0400  193.8800  193.8800
       2024-12-28 00:55:00+00:00  193.880  193.9800  193.8667  193.9800

                                   volume  trade_count        vwap
symbol timestamp
GOOG   2024-09-19 12:30:00+00:00   6036.0        154.0  164.495829
       2024-09-19 12:35:00+00:00  10308.0        196.0  164.551115
       2024-09-19 12:40:00+00:00   8804.0        120.0  164.623594
       2024-09-19 12:45:00+00:00  14154.0        213.0  164.611847
       2024-09-19 12:50:00+00:00   3051.0         59.0  164.538626
...                                   ...          ...         ...
       2024-12-28 00:25:00+00:00    292.0         23.0  194.210000
       2024-12-28 00:40:00+00:00    532.0         12.0  194.100000
       2024-12-28 00:45:00+00:00    592.0          9.0  194.033333
       2024-12-28 00:50:00+00:00   2378.0         64.0  193.994041
       2024-12-28 00:55:00+00:00   1268.0         19.0  193.894308

[11422 rows x 7 columns]

In [25]:
history_df1.reset_index().drop('symbol',axis=1).set_index('timestamp')

,open,high,low,close,volume,trade_count,vwap
timestamp,,,,,,,
2024-12-16 09:00:00+00:00,191.4400,192.35,191.4400,191.4900,2354.0,133.0,191.722990
2024-12-16 09:01:00+00:00,191.7800,191.78,191.3800,191.3800,4130.0,80.0,191.437211
2024-12-16 09:02:00+00:00,191.7000,191.70,191.6000,191.6000,2167.0,50.0,191.674555
2024-12-16 09:04:00+00:00,191.6000,191.60,191.6000,191.6000,637.0,23.0,191.600000
2024-12-16 09:06:00+00:00,191.8500,191.85,191.8500,191.8500,790.0,22.0,191.850000
...,...,...,...,...,...,...,...
2024-12-16 18:07:00+00:00,199.6648,199.90,199.6500,199.8050,25913.0,558.0,199.783331
2024-12-16 18:08:00+00:00,199.7909,199.88,199.5650,199.8586,37474.0,725.0,199.768444
2024-12-16 18:09:00+00:00,199.8666,200.12,199.8409,200.1000,623758.0,5735.0,199.999944
2024-12-16 18:10:00+00:00,200.0900,200.18,200.0100,200.1500,63270.0,970.0,200.088011
2024-12-16 18:11:00+00:00,200.1600,200.38,200.1400,200.3600,67704.0,979.0,200.261235

# crypto

In [28]:
from alpaca.data.historical.crypto import CryptoHistoricalDataClient
# setup crypto historical data client
crypto_historical_data_client = CryptoHistoricalDataClient()

In [47]:
from alpaca.data.requests import CryptoBarsRequest
# get historical bars by symbol
# ref. https://docs.alpaca.markets/reference/cryptobars-1
symbol = "BTC/USD"
now = datetime.now(ZoneInfo("America/New_York"))
req = CryptoBarsRequest(
    symbol_or_symbols = [symbol],
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Minute), # specify timeframe
    start = now - timedelta(days = 1),                          # specify start datetime, default=the beginning of the current day.
    # end_date=None,                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)
history_df2=crypto_historical_data_client.get_crypto_bars(req).df
history_df2

                                          open         high          low  \
symbol  timestamp
BTC/USD 2024-12-15 18:41:00+00:00  103275.9755  103275.9755  103225.1050
        2024-12-15 18:42:00+00:00  103239.9100  103260.1000  103193.8450
        2024-12-15 18:43:00+00:00  103195.4300  103243.6910  103182.8150
        2024-12-15 18:44:00+00:00  103216.7050  103254.8255  103216.7050
        2024-12-15 18:45:00+00:00  103211.9075  103267.6265  103211.9075
...                                        ...          ...          ...
        2024-12-16 18:35:00+00:00  107596.1550  107596.1550  107596.1550
        2024-12-16 18:36:00+00:00  107639.6685  107745.2770  107639.6685
        2024-12-16 18:37:00+00:00  107812.2740  107812.2740  107722.6450
        2024-12-16 18:38:00+00:00  107650.0000  107650.0000  107570.1900
        2024-12-16 18:39:00+00:00  107500.0000  107570.1900  107500.0000

                                        close    volume  trade_count  \
symbol  timestamp
BTC/USD 2024-12-15 18:41:00+00:00  103225.105  0.000000          0.0
        2024-12-15 18:42:00+00:00  103193.845  0.000000          0.0
        2024-12-15 18:43:00+00:00  103218.716  0.000000          0.0
        2024-12-15 18:44:00+00:00  103243.297  0.000000          0.0
        2024-12-15 18:45:00+00:00  103258.990  0.000000          0.0
...                                       ...       ...          ...
        2024-12-16 18:35:00+00:00  107596.155  0.000000          0.0
        2024-12-16 18:36:00+00:00  107745.277  0.000000          0.0
        2024-12-16 18:37:00+00:00  107722.645  0.000009          1.0
        2024-12-16 18:38:00+00:00  107570.190  0.000000          0.0
        2024-12-16 18:39:00+00:00  107570.190  0.000009          1.0

                                           vwap
symbol  timestamp
BTC/USD 2024-12-15 18:41:00+00:00       0.00000
        2024-12-15 18:42:00+00:00       0.00000
        2024-12-15 18:43:00+00:00       0.00000
        2024-12-15 18:44:00+00:00       0.00000
        2024-12-15 18:45:00+00:00       0.00000
...                                         ...
        2024-12-16 18:35:00+00:00  107596.15500
        2024-12-16 18:36:00+00:00  107692.47275
        2024-12-16 18:37:00+00:00  107812.27400
        2024-12-16 18:38:00+00:00  107610.09500
        2024-12-16 18:39:00+00:00  107500.00000

[1126 rows x 7 columns]

In [35]:
history_df2.reset_index().drop('symbol',axis=1).set_index('timestamp')

,open,high,low,close,volume,trade_count,vwap
timestamp,,,,,,,
2024-12-15 18:33:00+00:00,103145.080000,103162.680000,103042.520000,103162.680000,0.005425,1.0,103042.520000
2024-12-15 18:34:00+00:00,103192.501427,103192.846428,103165.900000,103192.846428,0.000000,0.0,0.000000
2024-12-15 18:35:00+00:00,103205.221428,103206.101428,103205.221428,103206.101428,0.000000,0.0,0.000000
2024-12-15 18:36:00+00:00,103219.488928,103219.488928,103219.488928,103219.488928,0.000000,0.0,0.000000
2024-12-15 18:37:00+00:00,103224.972428,103225.444927,103224.972428,103225.444927,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...
2024-12-16 18:26:00+00:00,107568.400000,107692.284000,107568.400000,107692.284000,0.003164,1.0,107568.400000
2024-12-16 18:28:00+00:00,107732.440000,107746.220000,107732.440000,107746.220000,0.000000,0.0,107739.330000
2024-12-16 18:29:00+00:00,107734.109000,107762.664616,107734.109000,107762.664616,0.008000,1.0,107750.000000
2024-12-16 18:30:00+00:00,107716.765000,107953.400000,107688.510000,107800.050000,0.108339,6.0,107942.798922
2024-12-16 18:31:00+00:00,107763.130000,107763.130000,107763.130000,107763.130000,0.000000,0.0,107763.130000

# option

In [48]:

from alpaca.data.historical.option import OptionHistoricalDataClient
from alpaca.data.requests import OptionBarsRequest
# setup option historical data client
option_historical_data_client = OptionHistoricalDataClient(api_key, secret_key)
symbol='SPY241216C00605000'
# get options historical bars by symbol
req = OptionBarsRequest(
    symbol_or_symbols = symbol,
    timeframe = TimeFrame(amount = 1, unit = TimeFrameUnit.Minute),   # specify timeframe
    start = now - timedelta(days = 1),                              # specify start datetime, default=the beginning of the current day.
    # end_date=None,                                                # specify end datetime, default=now
    # limit = 2,                                                      # specify limit
)
history_df3=option_historical_data_client.get_option_bars(req).df
history_df3

                                              open  high   low  close  volume  \
symbol             timestamp
SPY241216C00605000 2024-12-16 14:30:00+00:00  1.43  1.74  1.41   1.44  2701.0
                   2024-12-16 14:31:00+00:00  1.42  1.67  1.42   1.45  2192.0
                   2024-12-16 14:32:00+00:00  1.47  1.49  1.29   1.35  2113.0
                   2024-12-16 14:33:00+00:00  1.34  1.45  1.28   1.28   400.0
                   2024-12-16 14:34:00+00:00  1.29  1.50  1.28   1.35   753.0
...                                            ...   ...   ...    ...     ...
                   2024-12-16 18:21:00+00:00  2.50  2.53  2.46   2.50   106.0
                   2024-12-16 18:22:00+00:00  2.50  2.60  2.49   2.60   179.0
                   2024-12-16 18:23:00+00:00  2.56  2.67  2.56   2.60    34.0
                   2024-12-16 18:24:00+00:00  2.60  2.68  2.60   2.67    54.0
                   2024-12-16 18:25:00+00:00  2.70  2.70  2.60   2.65    17.0

                                              trade_count      vwap
symbol             timestamp
SPY241216C00605000 2024-12-16 14:30:00+00:00        405.0  1.591385
                   2024-12-16 14:31:00+00:00        299.0  1.510465
                   2024-12-16 14:32:00+00:00        200.0  1.375002
                   2024-12-16 14:33:00+00:00         93.0  1.391375
                   2024-12-16 14:34:00+00:00        113.0  1.358964
...                                                   ...       ...
                   2024-12-16 18:21:00+00:00         14.0  2.495377
                   2024-12-16 18:22:00+00:00         24.0  2.541006
                   2024-12-16 18:23:00+00:00         22.0  2.623235
                   2024-12-16 18:24:00+00:00          7.0  2.643704
                   2024-12-16 18:25:00+00:00         10.0  2.649412

[230 rows x 7 columns]

In [45]:
history_df3.reset_index().drop('symbol',axis=1).set_index('timestamp')

,open,high,low,close,volume,trade_count,vwap
timestamp,,,,,,,
2024-12-16 14:30:00+00:00,1.43,1.74,1.41,1.44,2701.0,405.0,1.591385
2024-12-16 14:31:00+00:00,1.42,1.67,1.42,1.45,2192.0,299.0,1.510465
2024-12-16 14:32:00+00:00,1.47,1.49,1.29,1.35,2113.0,200.0,1.375002
2024-12-16 14:33:00+00:00,1.34,1.45,1.28,1.28,400.0,93.0,1.391375
2024-12-16 14:34:00+00:00,1.29,1.50,1.28,1.35,753.0,113.0,1.358964
...,...,...,...,...,...,...,...
2024-12-16 18:20:00+00:00,2.45,2.48,2.44,2.44,44.0,9.0,2.459545
2024-12-16 18:21:00+00:00,2.50,2.53,2.46,2.50,106.0,14.0,2.495377
2024-12-16 18:22:00+00:00,2.50,2.60,2.49,2.60,179.0,24.0,2.541006
2024-12-16 18:23:00+00:00,2.56,2.67,2.56,2.60,34.0,22.0,2.623235
2024-12-16 18:24:00+00:00,2.60,2.68,2.60,2.67,54.0,7.0,2.643704

In [41]:
from alpaca.trading.requests import GetOptionContractsRequest
from alpaca.trading.enums import AssetStatus
from alpaca.trading.client import TradingClient
# setup clients
trade_client = TradingClient(api_key=api_key, secret_key=secret_key)

# get list of options contracts for the given underlying symbol (e.g. SPY,AAPL)
# - get_option_contracts() is a new method to get list of options contracts
# - in this example, we get 2 options contracts for SPY,AAPL
# - you can continue to fetch options contracts by specifying page_token from next_page_token of response
underlying_symbols = ["SPY"]
req = GetOptionContractsRequest(
    underlying_symbols = underlying_symbols,               # specify underlying symbols
    status = AssetStatus.ACTIVE,                           # specify asset status: active (default)
    expiration_date = None,                                # specify expiration date (specified date + 1 day range)
    expiration_date_gte = None,                            # we can pass date object
    expiration_date_lte = None,                            # or string (YYYY-MM-DD)
    root_symbol = None,                                    # specify root symbol
    type = None,                                           # specify option type (ContractType.CALL or ContractType.PUT)
    style = None,                                          # specify option style (ContractStyle.AMERICAN or ContractStyle.EUROPEAN)
    strike_price_gte = None,                               # specify strike price range
    strike_price_lte = None,                               # specify strike price range
    limit = 2,                                             # specify limit
    page_token = None,                                     # specify page token
)
res = trade_client.get_option_contracts(req)
res

{   'next_page_token': 'Mg==',
    'option_contracts': [   {   'close_price': '204.69',
                                'close_price_date': datetime.date(2024, 12, 13),
                                'expiration_date': datetime.date(2024, 12, 16),
                                'id': '4ae4946c-91a5-4f3c-af4d-63f01222d5a1',
                                'name': 'SPY Dec 16 2024 400 Call',
                                'open_interest': '15',
                                'open_interest_date': datetime.date(2024, 12, 12),
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 400.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY241216C00400000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2024, 12, 16),
                                'id': 'cdb93e5b-a246-44aa-8ded-72df6c2e3b61',
                                'name': 'SPY Dec 16 2024 405 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 405.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY241216C00405000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'}]}